# Generated by Django 6.0.3 on 2026-04-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=2)),
                ('professor', models.CharField(blank=True, max_length=200)),
                ('schedule_code', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(choices=[(211, 'Monday - 08:00 to 08:55'), (212, 'Monday - 08:55 to 09:50'), (213, 'Monday - 10:00 to 10:55'), (214, 'Monday - 10:55 to 11:50'), (215, 'Monday - 12:00 to 12:55'), (221, 'Monday - 12:55 to 13:50'), (222, 'Monday - 14:00 to 14:55'), (223, 'Monday - 14:55 to 15:50'), (224, 'Monday - 16:00 to 16:55'), (225, 'Monday - 16:55 to 17:50'), (226, 'Monday - 18:00 to 18:55'), (227, 'Monday - 18:55 to 19:50'), (231, 'Monday - 19:00 to 19:50'), (232, 'Monday - 19:50 to 20:40'), (233, 'Monday - 20:50 to 21:40'), (234, 'Monday - 21:40 to 22:30'), (311, 'Tuesday - 08:00 to 08:55'), (312, 'Tuesday - 08:55 to 09:50'), (313, 'Tuesday - 10:00 to 10:55'), (314, 'Tuesday - 10:55 to 11:50'), (315, 'Tuesday - 12:00 to 12:55'), (321, 'Tuesday - 12:55 to 13:50'), (322, 'Tuesday - 14:00 to 14:55'), (323, 'Tuesday - 14:55 to 15:50'), (324, 'Tuesday - 16:00 to 16:55'), (325, 'Tuesday - 16:55 to 17:50'), (326, 'Tuesday - 18:00 to 18:55'), (327, 'Tuesday - 18:55 to 19:50'), (331, 'Tuesday - 19:00 to 19:50'), (332, 'Tuesday - 19:50 to 20:40'), (333, 'Tuesday - 20:50 to 21:40'), (334, 'Tuesday - 21:40 to 22:30'), (411, 'Wednesday - 08:00 to 08:55'), (412, 'Wednesday - 08:55 to 09:50'), (413, 'Wednesday - 10:00 to 10:55'), (414, 'Wednesday - 10:55 to 11:50'), (415, 'Wednesday - 12:00 to 12:55'), (421, 'Wednesday - 12:55 to 13:50'), (422, 'Wednesday - 14:00 to 14:55'), (423, 'Wednesday - 14:55 to 15:50'), (424, 'Wednesday - 16:00 to 16:55'), (425, 'Wednesday - 16:55 to 17:50'), (426, 'Wednesday - 18:00 to 18:55'), (427, 'Wednesday - 18:55 to 19:50'), (431, 'Wednesday - 19:00 to 19:50'), (432, 'Wednesday - 19:50 to 20:40'), (433, 'Wednesday - 20:50 to 21:40'), (434, 'Wednesday - 21:40 to 22:30'), (511, 'Thursday - 08:00 to 08:55'), (512, 'Thursday - 08:55 to 09:50'), (513, 'Thursday - 10:00 to 10:55'), (514, 'Thursday - 10:55 to 11:50'), (515, 'Thursday - 12:00 to 12:55'), (521, 'Thursday - 12:55 to 13:50'), (522, 'Thursday - 14:00 to 14:55'), (523, 'Thursday - 14:55 to 15:50'), (524, 'Thursday - 16:00 to 16:55'), (525, 'Thursday - 16:55 to 17:50'), (526, 'Thursday - 18:00 to 18:55'), (527, 'Thursday - 18:55 to 19:50'), (531, 'Thursday - 19:00 to 19:50'), (532, 'Thursday - 19:50 to 20:40'), (533, 'Thursday - 20:50 to 21:40'), (534, 'Thursday - 21:40 to 22:30'), (611, 'Friday - 08:00 to 08:55'), (612, 'Friday - 08:55 to 09:50'), (613, 'Friday - 10:00 to 10:55'), (614, 'Friday - 10:55 to 11:50'), (615, 'Friday - 12:00 to 12:55'), (621, 'Friday - 12:55 to 13:50'), (622, 'Friday - 14:00 to 14:55'), (623, 'Friday - 14:55 to 15:50'), (624, 'Friday - 16:00 to 16:55'), (625, 'Friday - 16:55 to 17:50'), (626, 'Friday - 18:00 to 18:55'), (627, 'Friday - 18:55 to 19:50'), (631, 'Friday - 19:00 to 19:50'), (632, 'Friday - 19:50 to 20:40'), (633, 'Friday - 20:50 to 21:40'), (634, 'Friday - 21:40 to 22:30'), (711, 'Saturday - 08:00 to 08:55'), (712, 'Saturday - 08:55 to 09:50'), (713, 'Saturday - 10:00 to 10:55'), (714, 'Saturday - 10:55 to 11:50'), (715, 'Saturday - 12:00 to 12:55'), (721, 'Saturday - 12:55 to 13:50'), (722, 'Saturday - 14:00 to 14:55'), (723, 'Saturday - 14:55 to 15:50'), (724, 'Saturday - 16:00 to 16:55'), (725, 'Saturday - 16:55 to 17:50'), (726, 'Saturday - 18:00 to 18:55'), (727, 'Saturday - 18:55 to 19:50'), (731, 'Saturday - 19:00 to 19:50'), (732, 'Saturday - 19:50 to 20:40'), (733, 'Saturday - 20:50 to 21:40'), (734, 'Saturday - 21:40 to 22:30')])),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='cronograde.classsection')),
            ],
        ),
        migrations.AddField(
            model_name='classsection',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='cronograde.subject'),
        ),
    ]
